In [2]:
import numpy as np

# Machine Learning needs:
    -
     Python
    -Numpy
    -Pandas
    -MatplotLib
    -Seaborn
    -Scikit-Learn
    
# Deep Learning needs:
    -
     Keras
    -TensorFlow
    -Scikit-Learn/Sklearn
    -Pytorch

# Computer Vision needs:
    -
     TensorFlow
    -Keras
    -Pytorch
    -OpenCV
    -Seaborn
    -Scikit-Learn

# Natual Language Processing needs:
    -
     Pandas
    -Numpy
    -NLTK
    -Tensorflow
    -Seaborn
    -Scikit-Learn


# About "Shape of Array"

 - "Reshaping" means 'changing the shape of an array' .

 - The shape of array defines the number of elements in each dimension.

 - with the help of reshaping of array we can add or remove dimensions of    array or change the number in each dimension.

Reshape from 1-D to 2-D array

In [4]:
arr = np.array ( [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] )
print( arr.ndim)
arr

1


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [12]:
# matrix    [ 1, 2, 3,         prc. try to elaborate matrix  
#                4, 5, 6,
#                7, 8, 9,
#               10, 11, 12] '''

In [6]:
arr2 = arr.reshape(4,3) # change 1-D array in 2-D array

In [7]:
print(arr2.ndim)
arr2

2


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
arr3 = arr.reshape(3,2) # prc. try different combinations for 2-D array
print(arr3.ndim)
arr3

2


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

- 1.axis
- 2.rows
- 3.colomns

Reshape from 1-D to 3-D array

In [17]:
arr = np.array ( [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] )
print(arr.ndim)

1


In [15]:
array3 = arr.reshape (2,3,2)  #prc. discuss various combinations for 3-D

In [26]:
print(array3)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [22]:
print(array3.ndim)

3
